### ISSUE TITLE
bug after obfuscation

### ISSUE THREAD

**Issue by XeniumNetwork** [FeepsDev/BSP-TexInfo-Obfuscator#1]
Hello,
I have a problem with the tool. After using it on the map, the map has a bug on the sounds. for example a metal noise on wood. And some parts of the map become dark.
Can you fix this please?

**Comment by FeepsDev** [comment]
This isn't an issue, please read the README.md. You must use the Flags Method.

**Comment by XeniumNetwork** [comment]
Yes i have try it, but i have sound bug

**Comment by FeepsDev** [comment]
The sound is linked to the Surface Prop, so when choosing texture, you need to make sure that you select the correct one that have the similar/exact sound.

**Comment by XeniumNetwork** [comment]
How to make the right choice with +600 textures and no information on which basic texture is linked
